services:
  nginx:
    image: nginx:alpine
    container_name: shared-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./www:/var/www/html:ro
    networks:
      - content-shared

networks:
  content-shared:
    external: true
